<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"床位管理",
                        "menuJump":"列表",
                        "tableName":"chuangwei"
                    }
                ],
                "menu":"床位管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"费用类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryFeiyong"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告信息类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"薪资类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXinzi"
                    }

                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"费用管理",
                        "menuJump":"列表",
                        "tableName":"feiyong"
                    }
                ],
                "menu":"费用管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"护工管理",
                        "menuJump":"列表",
                        "tableName":"hugong"
                    }
                ],
                "menu":"护工管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "审核",
                            "删除"
                        ],
                        "menu":"请假管理",
                        "menuJump":"列表",
                        "tableName":"qingjia"
                    }
                ],
                "menu":"请假管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
	                        "审核",
                            "删除"
                        ],
                        "menu":"外出请求管理",
                        "menuJump":"列表",
                        "tableName":"waichuqingqiu"
                    }
                ],
                "menu":"外出请求管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"薪资管理",
                        "menuJump":"列表",
                        "tableName":"xinzi"
                    }
                ],
                "menu":"薪资管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"老人管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"老人管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"床位管理",
	                    "menuJump":"列表",
	                    "tableName":"chuangwei"
	                }
	            ],
	            "menu":"床位管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"费用管理",
	                    "menuJump":"列表",
	                    "tableName":"feiyong"
	                }
	            ],
	            "menu":"费用管理"
	        },
			{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "删除"
	                    ],
	                    "menu":"请假管理",
	                    "menuJump":"列表",
	                    "tableName":"qingjia"
	                }
	            ],
	            "menu":"请假管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "审核"
	                    ],
	                    "menu":"外出请求管理",
	                    "menuJump":"列表",
	                    "tableName":"waichuqingqiu"
	                }
	            ],
	            "menu":"外出请求管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"薪资管理",
	                    "menuJump":"列表",
	                    "tableName":"xinzi"
	                }
	            ],
	            "menu":"薪资管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"护工",
	    "tableName":"hugong"
	},
	{
	    "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"床位管理",
			            "menuJump":"列表",
			            "tableName":"chuangwei"
			        }
			    ],
			    "menu":"床位管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"费用管理",
			            "menuJump":"列表",
			            "tableName":"feiyong"
			        }
			    ],
			    "menu":"费用管理"
			},
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "删除"
	                    ],
	                    "menu":"外出请求管理",
	                    "menuJump":"列表",
	                    "tableName":"waichuqingqiu"
	                }
	            ],
	            "menu":"外出请求管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"老人",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
